FROM centos:8

WORKDIR $HOME

RUN dnf install -y epel-release; \
    dnf install -y python3; \
	alternatives --set python /usr/bin/python3 \

USER root

EXPOSE $NOVNC_PORT

# Define default command.
CMD ["bootstrap_openbox.sh"]
