FROM bayonetc/ubuntu-xfce
MAINTAINER Jerend Cao "bayonet_c1@163.com"

ENV CALIBRE_PORT=8080

USER root

## Install software
RUN wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin

VOLUME ["/library"]

EXPOSE $CALIBRE_PORT
